### ISSUE TITLE
Can't draw because locationX doesn't change on Android

### ISSUE THREAD

**Issue by linytsysu** [liuhong1happy/react-native-scrawl#1]
I find I can't draw because locationX doesn't change on Android. See this bug in react-native: [PanResponder e.nativeEvent BUG ANDROID](https://github.com/facebook/react-native/issues/12282)

**Comment by liuhong1happy** [comment]
暂时不清楚 pageX 和 locationX 含义是否一致，如果可以你修改下源码，再提交pr吧。
@linytsysu

**Comment by linytsysu** [comment]
pageX和locationX的含义是不一致的。事实上，这是由于React Native本身的bug引起的，这个项目源码逻辑上本身是没有问题的。

**Comment by liuhong1happy** [comment]
0.2.0版本已经解决该问题
